// web/src/components/header/Header.tsx
import React, { useState } from "react";
import './header.scss';
import { Navbar } from "../../App";

const Header: React.FC<{ setSearchQuery: Function, navbar: Navbar[], setNavbar: Function }> = ({ setSearchQuery, navbar, setNavbar }) => {
    return (
        <div className="header">
            <div className="logo">
                <p className="title">Administrator Panel</p>
                <p className="description">All Commands</p>
            </div>
            <div className="navbar">
                {navbar.map((nav, index) => (
                    <p 
                    onClick={() => setNavbar((prev: Navbar[]) => prev.map((n) => n.name === nav.name ? { ...n, isActive: true } : { ...n, isActive: false }))} 
                    className={`nav-item ${nav.isActive && `nav-active`}`} key={`nav-${index}`}
                    >
                        {nav?.label || nav.name.toUpperCase()}
                    </p>
                ))}
            </div>
            <div className="search-wrapper">
                <input onChange={(e) => setSearchQuery(e.target.value)} type="text" placeholder="Search"/>
                <i className="fa-solid fa-magnifying-glass"></i>
            </div>
            <div className="exit">
                <p>Exit</p>
                <p>ESC</p>
            </div>
        </div>
    )
};

export default Header

// web/src/lib/components/header/Header.svelte
<script lang="ts">
import { Locale } from "$lib/store/locale";
import Categories from "../categories/Categories.svelte";
import './header.scss'

const { category, searchQuery } = $props();
</script>

<div class="header">
    <div class="info">
        <p class="title">{Locale.admin_panel || 'Administrator Panel'}</p>
        <p class="description">{Locale.all_commands || 'All Commands'}</p>
    </div>
    <Categories category={category} />
    <div class="input-wrapper">
        <input type="text" placeholder={Locale.search || 'Search...'} oninput={(e: Event) => searchQuery((e.target as HTMLInputElement).value)}>
        <i class="fa-solid fa-magnifying-glass"></i>
    </div>
    <div class="exit-wrapper">
        <p class="exit">{Locale.exit || 'Exit'}</p>
        <p>ESC</p>
    </div>
</div>
