// web/src/components/Dashboard.tsx
import { Locale } from '../store/locale';
import { type AdminMenu } from '../typings/adminMenu';
import DashboardChart from './DashboardChart';

const Dashboard: React.FC<{
  props: AdminMenu;
  allPlayers: Function;
}> = ({ props, allPlayers }) => {
  return (
    <div className="flex flex-col gap-3 pr-10 h-full">
      <div className="text-white h-1/2 flex gap-3">
        <div className="bg-neutral-900 w-2/3 p-5 rounded-lg border border-neutral-700 h-fit">
          <div className="flex items-center justify-between">
            <p className="font-semibold">{Locale.current_players || 'Current Players on Server'}</p>
            <p className="text-lime-500 font-bold text-xl">{props.players.total}</p>
          </div>
          <div className="my-5 flex gap-3 flex-wrap max-h-[152px] overflow-auto">
            <div className="flex gap-3 items-center text-yellow-300 bg-yellow-400/10 w-fit px-2 py-1 rounded-md border border-yellow-300 text-sm">
              <p>{Locale.doj || 'DOJ'}</p>
              <p className="text-white font-bold">{props.players.doj || 0}</p>
            </div>
            <div className="flex gap-3 items-center text-red-300 bg-red-500/10 w-fit px-2 py-1 rounded-md border border-red-500 text-sm">
              <p>{Locale.medical || 'Medical'}</p>
              <p className="text-white font-bold">{props.players.medical || 0}</p>
            </div>
            <div className="flex gap-3 items-center text-blue-500 bg-blue-500/10 w-fit px-2 py-1 rounded-md border border-blue-500 text-sm">
              <p>{Locale.police || 'Police'}</p>
              <p className="text-white font-bold">{props.players.police || 0}</p>
            </div>
          </div>
          <div>
            <button
              onClick={() => allPlayers()}
              className="text-sm font-medium bg-neutral-800 px-4 py-1.5 rounded-full border border-neutral-700
                        hover:bg-neutral-200/10 hover:border-neutral-600 duration-200"
            >
              {Locale.all_players || 'All Players'}
            </button>
          </div>
        </div>
        <div className="bg-neutral-900 w-1/3 p-5 pr-0 rounded-lg border border-neutral-700">
          <div className="flex items-center justify-between pr-5">
            <p className="font-semibold">{Locale.admins_online || 'Admins Online'}</p>
            <p className="text-lime-500 font-bold text-xl">{props.admins.length}</p>
          </div>
          <div className="flex flex-col gap-3 mt-3 overflow-auto max-h-56 pr-5">
            {props.admins.map((admin, index) => (
              <div
                key={`admin-${index}`}
                className="bg-neutral-800 border border-neutral-700 rounded-md py-1.5 px-2 text-sm flex items-center justify-between cursor-pointer group"
              >
                <p className="group-hover:text-lime-500 duration-200">{admin.name}</p>
                <p className="bg-lime-900/70 border border-lime-500 rounded-lg px-1.5 py-0.5 text-[12px]">
                  {admin.label || admin.role.charAt(0).toUpperCase() + admin.role.slice(1)}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="bg-neutral-900 w-full p-5 rounded-lg border border-neutral-700 h-1/2">
        <p className="text-white font-semibold mb-5">{Locale.players_activity || 'Players Activity'}</p>
        <DashboardChart data={props.dashboard} />
      </div>
    </div>
  );
};

export default Dashboard;

// web/src/lib/components/tabs/Dashboard.svelte
<script lang="ts">
import type { AdminData } from '$lib/state/admin';

export let admin: AdminData;
export let allPlayers;
</script>

<div class="w-full h-full">
    <div class="w-full h-1/2 flex gap-5">
        <div class="bg-gradient-to-br from-black/50 to-lime-900/20 border border-lime-800 rounded-md w-2/3 h-fit p-5 text-white font-[Inter]">
            <div class="flex justify-between items-center">
                <p class="font-semibold text-lg">Current Players on Server</p>
                <p class="font-bold text-2xl text-lime-400">91</p>
            </div>
            <div class="my-5 flex gap-3 flex-wrap overflow-auto max-h-32">
                <div class="flex items-center gap-4 border border-red-500 w-fit px-3 py-1.5 rounded-lg bg-gradient-to-b from-red-900/50 to-red-500/50">
                    <p class="text-red-300 font-light">Medical</p>
                    <p class="font-bold">3</p>
                </div>
                <div class="flex items-center gap-4 border border-blue-500 w-fit px-3 py-1.5 rounded-lg bg-gradient-to-b from-blue-900/50 to-blue-500/50">
                    <p class="text-blue-300 font-light">Police</p>
                    <p class="font-bold">2</p>
                </div>
                <div class="flex items-center gap-4 border border-yellow-500 w-fit px-3 py-1.5 rounded-lg bg-gradient-to-b from-yellow-900/50 to-yellow-500/50">
                    <p class="text-yellow-100 font-light">DOJ</p>
                    <p class="font-bold">0</p>
                </div>
            </div>
            <div>
                <div onclick={allPlayers} class="bg-neutral-100/15 border border-neutral-400 w-fit rounded-full px-4 py-1.5 cursor-pointer duration-200 hover:border-lime-500 hover:bg-lime-500/10">All Players</div>
            </div>
        </div>
        <div class="bg-gradient-to-br from-black/50 to-lime-900/20 w-1/3 h-full rounded-md border border-lime-800 pt-5 pl-5 pb-5 font-[Inter] text-white">
            <div class="flex justify-between items-center pr-5">
                <p class="font-semibold">Admins Online</p>
                <p class="font-bold text-2xl text-lime-400">{(admin.online?.length || 0) + 1}</p>
            </div>
            <div class="mt-3 flex flex-col gap-3 h-[85%] overflow-auto pr-5">
                <div class="flex justify-between bg-neutral-100/15 px-3 py-2 border border-neutral-400 rounded-lg items-center">
                    <p>{admin.nickname}</p>
                    <p class="bg-lime-950/70 px-2 py-1 font-light text-sm border border-lime-500 rounded-lg">{admin.role.charAt(0).toUpperCase() + admin.role.slice(1)}</p>
                </div>

                {#if admin.online}
                    {#each admin.online as user}
                        <div class="flex justify-between bg-neutral-100/15 px-3 py-2 border border-neutral-400 rounded-lg items-center">
                            <p class="w-1/2 line-clamp-3">{user.nickname}</p>
                            <p class="bg-lime-950/70 px-2 py-1 border font-light text-sm border-lime-500 rounded-lg">{user.role.charAt(0).toUpperCase() + user.role.slice(1)}</p>
                        </div>
                    {/each}
                {/if}
            </div>
        </div>
    </div>
    <div>

    </div>
</div>
